FROM debian:jessie

RUN apt-get update && \
    apt-get install -y \
        nodejs \
        nodejs-legacy \
        npm \
        git \
        wget && rm -rf /var/lib/apt/lists/*

ENV NVM_DIR /usr/local/nvm

RUN wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash && \
    . $NVM_DIR/nvm.sh && \
    nvm install 6.9.1

ENV PATH $NVM_DIR/versions/node/v6.9.1/bin:$PATH
